"$schema" = 'https://starship.rs/config-schema.json'

palette = "catppuccin_macchiato"

add_newline = true

format = """
$username\
$directory\
$git_branch\
$git_status\
$fill\
$cmd_duration\
$time\
$line_break\
$status\
$character\
"""

[palettes.catppuccin_macchiato]
rosewater = "#f4dbd6"
flamingo = "#f0c6c6"
pink = "#f5bde6"
mauve = "#c6a0f6"
red = "#ed8796"
maroon = "#ee99a0"
peach = "#f5a97f"
yellow = "#eed49f"
green = "#a6da95"
teal = "#8bd5ca"
sky = "#91d7e3"
sapphire = "#7dc4e4"
blue = "#8aadf4"
lavender = "#b7bdf8"
text = "#cad3f5"
subtext1 = "#b8c0e0"
subtext0 = "#a5adcb"
overlay2 = "#939ab7"
overlay1 = "#8087a2"
overlay0 = "#6e738d"
surface2 = "#5b6078"
surface1 = "#494d64"
surface0 = "#363a4f"
base = "#24273a"
mantle = "#1e2030"
crust = "#181926"

[character]
success_symbol = "[⌘](bold teal)"
error_symbol = "[⌘](bold maroon)"

[cmd_duration]
min_time = 1000
style = "teal bold"
format = "[ $duration]($style) "

[directory]
style = "bold mauve"
format = "[$path ]($style)"
truncation_symbol = ".../"

[fill]
style = "surface1"
symbol = "."

[git_branch]
style = "flamingo"
symbol = " "
format = "[$symbol$branch ]($style)"

[git_status]
style = "bold lavender"
deleted = "-"
staged = "+$count"
format = "[$untracked$modified$deleted$staged$ahead_behind]($style)"

[username]
show_always = true
format = "[$user ]($style)"
disabled = true

[hostname]
ssh_only = false
format = "[$hostname](bold bright-green) "

[os.symbols]
Macos = "󰀵 "

[os]
format = "$symbol"
disabled = false

[status]
disabled = false
failure_style = "maroon"
format = "[$status $common_meaning ]($style)"

[time]
style = "bold peach"
time_format = "%R"
format = "[ $time]($style)"
disabled = false
