"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true

format = """
$username\
$directory\
$git_branch\
$git_status\
$fill\
$time\
$line_break\
$character\
"""

# right_format = """"""

[character]
success_symbol = '[⌘](bright-blue bold)'
error_symbol = "[⌘](bright-red bold)"

[directory]
format = "[$path]($style) "
truncation_symbol = ".../"

[git_branch]
style = "bold bright-purple"
symbol = " "
format = "[$symbol$branch ]($style)"

[git_status]
format = "[$ahead_behind]($style)"

[username]
show_always = true
style_user = "red bold"
format = "[$user ]($style)"

[hostname]
ssh_only = false
format = "[$hostname](bold bright-green) "

[os.symbols]
Macos = "󰀵 "

[os]
format = "$symbol"
disabled = false

[time]
style = "bold yellow"
time_format = "%R"
format = "[ $time]($style)"
disabled = false

[fill]
symbol = "."
